### ISSUE TITLE
a problem with trying TRiCoLOR on Nanopore sequencing data

### ISSUE THREAD

**Issue by FangfeiHu** [davidebolo1993/TRiCoLOR#7] opened 2021-02-25 10:59 UTC
Hi, My name is Fangfei and I'm interested in applying TRiCoLOR on a Nanopore sequencing data to find repeats. However I met a problem with the SENSoR step. Could you help me with it? 
The error message is ` ERROR: Requested column 4, but database file /tmp/pybedtools.4w9nhvb_.tmp only has fields 1 - 0.  `
<img width="1280" alt="tricolor_problem" src="https://user-images.githubusercontent.com/79637546/109143888-7ca8b700-779b-11eb-960d-e21aa6dc5be3.png">

I tried the test data in the use case you provided and it could work well. I'm wondering is there any specific requirement on the input bam format?

I use the Medaka_variant to do the variant calling and then get haplotagged bam file with WhatsHap.

By the way I also tried the prepare.sh you provided in TRiCoLOR/paper/data, but there is also a problem with `bcftools view -m2 -M2 -c 1 -C 1 -e 'GT[*] = "mis"' -O b -o ${id}.fixed.bcf ${id}.fixed.vcf.gz && rm ${id}.fixed.vcf.gz*`
The error message is `Failed to open HG00733.fixed.vcf.gz:unknown file type`.
This problem is also with the example data in prepare.sh. 

I'm wondering is there a way to solve any of these problems and make TRiCoLOR works for my data? 
Thank you very much.

Waiting for your reply.

Kind regards,
Fangfei

**Comment by davidebolo1993** [comment] 2021-02-25 11:37
Hi @FangfeiHu,

this is related to pybedtools, which is expecting a non-empty column 4 while merging. Also, from the messages that are printed, it seems to me that SENSoR is proceeding too fast on those chromosomes (it is fast, but not that fast usually). Is this a low-coverage BAM file? BTW, it would be nice if you can share your data (BAM and exclude.txt) so that I can try to reproduce the error.
Thanks,

Davide

**Comment by FangfeiHu** [comment] 2021-02-25 12:07
Hi @davidebolo1993, thank you for your reply. I remembered this is a low-coverage data and I'm going to double check with my supervisor and also about if it's possible to share the bam file.

**Comment by davidebolo1993** [comment] 2021-02-25 12:13
Yep, sharing (even a subsample) if possible would be great. 
Thanks,

Davide

**Comment by FangfeiHu** [comment] 2021-02-26 06:43
Hi @davidebolo1993 , I just got the reply from my supervisor. I tried to attach the files I used in a comment but the bam file is too big. I'm going to write you a email with the haplotagged bam file and the exclude.txt.

Thank you very much for helping me with it.

**Comment by davidebolo1993** [comment] 2021-02-26 08:37
Hi @FangfeiHu,

I gave your BAM file a quick look and I can say that there are few problems here. As mentioned above, the error you get is because pybedtools could not merge the BED-like file generated for haplotype 1 (non-empty) and the BED-like file generated for haplotype 2 (empty, and that's why this one is missing the 4th column). In turn, this happens because the default is to output low-entropy segments (20 bps) supported by at least 5 calls (--call 5). Below, is what you have for haplotype 1 in your (target) BAM:
``` bash
samtools view 20191118_Cas9_Barcoding_barcode06_pass_haplotagged.bam | grep "HP:i:1" | cut -f3
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr1
chr8
chr15
chr15
chr15
chr15
chr15
chr15
chr15
chr15
chr15
chr15
chr15
chr15
chr15
```
and for haplotype 2:

``` bash
samtools view 20191118_Cas9_Barcoding_barcode06_pass_haplotagged.bam | grep "HP:i:2" | cut -f3 
chr1
chr1
chr1
chr1
chr8
chr8
chr15
chr15
chr15
chr15
chr15
```
In practice, for the (few) reads that have a valid HP-tag in your BAM, SENSoR spots some low-entropy segments on haplotype1 (chr1) but nothing on the other chromosomes and on the other haplotype (where the number of overlapping low-entropy segments is lower than treshold). A workaround is to set the --call threshold to something like 2. This will spot additional low-entropy segments on haplotype 1 (chr15) and something on haplotype 2 (chr1).
However, I honestly don't recommend to call TRs on regions that have less than 5 supporting calls, mainly because, in my experience, having less than 5 reads during the consensus computation step does not improve the accuracy of the final consensus significantly. 
I hope this answers your question. I'm sorry I can't be more positive at the moment, but I'm happy to help if needed. 

Thanks,

Davide

**Comment by davidebolo1993** [comment] 2021-03-09 19:32
Closing for now. Feel free to re-open at any time.

**Closed by davidebolo1993** 2021-03-09 19:32 UTC
Labels: question
