### ISSUE TITLE
ApP Error |  IndexError: list index out of range

### ISSUE THREAD

**Issue by Tine-dk** [davidebolo1993/TRiCoLOR#4] opened 2020-08-12 13:52 UTC
Hi, I'm trying to use the ApP module. But I get the error below.
I'm not sure what is meant with "list index".
Is there anything I could do differently? 

Thanks in advance!
................................................................................................................................
The error message:
```
08/12/2020 03:41:03 PM ERROR Unexpected error while analyzing region 4:3074000-3078000. Log is below
Traceback (most recent call last):
  File "/miniconda/envs/tricolorenv/lib/python3.7/site-packages/TRiCoLOR-1.0.0-py3.7.egg/TRiCoLOR/ApP/ApP.py", line 122, in run
    Generate_Alignment_ToPlot(args.genome,bams,chromosome,start,end,args.genomebed,args.haplotypebed,label,args.output)
  File "/miniconda/envs/tricolorenv/lib/python3.7/site-packages/TRiCoLOR-1.0.0-py3.7.egg/TRiCoLOR/ApP/ApP.py", line 285, in Generate_Alignment_ToPlot
    bam2_coords,bam2_seq=Get_Alignment_Positions(os.path.abspath(hap_bam[1]),chromosome,start,end)
**IndexError: list index out of range**
```

I know there is something in the repetition bed-files:
```
4	3076604	3076636	CAG	9 #Haplotype1
4	3076607	3076666	CAG	19 #Haplotype2
```

The plot.bed was made like this:
` echo -e "4\t3074000\t3078000\tregion\nX\t146992000\t146995000\tregion" > plot.bed`

This is how I tried to run the ApP module:
```
TRiCoLOR ApP -g /resources/b37/human_g1k_v37_decoy.fasta \
-bam TRiCoLOR/GM06891_REFER/haplotype1/4.merged.srt.bam \
-bed plot.bed \
-o TRiCoLOR/GM06891_ApP_Illumina_Guided \
-gb TRiCoLOR/GM06891_REFER/reference/4.repetitions.bed \
-hb TRiCoLOR/GM06891_REFER/haplotype1/4.repetitions.bed TRiCoLOR/GM06891_REFER/haplotype2/4.repetitions.bed
```

**Comment by davidebolo1993** [comment] 2020-08-12 16:13
Hi @Tine-dk,

few errors I noticed here. 
First, you are trying to plot repetitions found on chromosomes 4 and X (see plot.bed) but you're giving as input only the BAM/BED files for chromosome  4  (see the ApP command you run). The line about chromosome X should be removed or the BAM files for chromosome 4 and X merged before running ApP.
Also, you're passing to the -bam flag only one BAM (TRiCoLOR/GM06891_REFER/haplotype1/4.merged.srt.bam) while this is expecting both (I guess the other one is 'TRiCoLOR/GM06891_REFER/haplotype2/4.merged.srt.bam'). This is what is causing the error you see.
Removing the line for chromosome X and adding the second BAM file to the -bam flag should solve your issue.

Best,

Davide

**Comment by Tine-dk** [comment] 2020-08-14 08:38
Thanks Davide for clearing things up for me! It works now. :D

Do you have any tips on how to interpret the highlighted regions in the HTML file?
This is one where the sample should look like the reference in this region. 
Haplotype 1 should have 19 repetitions of CAG, haplotype 2 should have 18 repetitions and the reference 19. 

The manuscript you have submitted to a peer-reviewed journal, is it available anywhere (e.g. on biorxiv.org)?

![GM20239_chr4](https://user-images.githubusercontent.com/67691621/90230126-59c73e80-de19-11ea-98e1-693b235648ca.PNG)

**Comment by davidebolo1993** [comment] 2020-08-14 08:48
Hi @Tine-dk,

Hopefully the manuscript will be out soon (I'll add the citation to the README once this is out). The ApP module is mainly intended for manual inspection of large differences between the 2 haplotypes and the reference. Small differences can be caused by sequencing errors that have not been resolved by the POA algorithm TRiCoLOR uses (more details in the upcoming manuscript).

Best,

Davide

**Closed by davidebolo1993** 2020-08-14 08:48 UTC
Labels: question
